Mobile set- up second section.
sheldonwafula/my-portfolio pull request #3
Opened 2023-01-13 16:07 UTC by sheldonwafula

In this pull request:
-I have created different sections using HTML.
-I have styled my project with CSS.
-I have created different layouts using flex and grid.
-I have corrected all linter errors.

2023-01-13 17:10 UTC, christianbiring1 requested changes
Hi @sheldonwafula , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/212377717-35d853a9-abf7-4bb4-9f08-81785f53defc.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 17:10 UTC, christianbiring1 commented on index.html
> +<div class="about">
- [ ] It would be nicer, to grab each specific section of the page in a `section` tag for semantic reasons. Be aware that a `div` is used where we don't have any semantic meaning.

2023-01-13 17:10 UTC, christianbiring1 commented on index.html
> +        <a href="#">LET'S CONNECT</a>
- [ ] Since the LET'S CONNECT is not a link redirecting anywhere, It would be great to use a heading `hx` or `div` element here

2023-01-13 17:10 UTC, christianbiring1 commented on index.html
> +            <p>CSS</p>
- [ ] Kindly make sure The technology categories (`Languages`, `Frameworks` and `Skills`) are in a `ul`, each of them in a `li` for semantic reasons since it is a list of elements 
- [ ] Also the technology in each category(e.g., `JavasScript`, `HTML` and `CSS`) are also a list `ul` and each of them a `li`

2023-01-14 10:01 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @sheldonwafula , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done really well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

**_Consider the comments below for the changes required._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 15:31 UTC, OyePriscilla approved these changes
Hi @sheldonwafula 😄, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
✔️Made the required changes👍
✔️No linter errors👍
✔️GitHub flow observed👍

## Optional suggestions

- [optional] **Generally, I think you need to pay more attention to details (most especially typography). You've done a very good job, but kindly ensure to reproduce what we have in the design template as close as possible. This will boost your confidence before hiring managers in case you're to replicate any design. ℹ️** **I noticed that the homepage, about-me and contact-me sections are not aligned properly, I suggest you work on this before you move on to the next milestone. 💁‍♂️** 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 15:31 UTC, OyePriscilla commented on index.html
> +            Myself</h1>
- [optional] Please kindly change this `h1` tag to any of the header tag `(h2, h3 ...)`; there should only be one `h1` tag in a HTML document for SEO optimization. 👍 Kindly adjust line 234 as well. 👍

2023-01-18 15:55 UTC, merged

2023-01-18 15:56 UTC, sheldonwafula commented
I will make the changes.